// Database types for MeuPersonal
// Generated from Supabase schema

export type Database = any; // Will be generated by Supabase CLI

// ============================================================================
// ACCOUNT TYPES
// ============================================================================

export type AccountType = 'admin' | 'professional' | 'managed_student' | 'autonomous_student';

export type AccountStatus = 'pending' | 'active' | 'rejected' | 'suspended';

export type ServiceType = 'personal_training' | 'nutrition_consulting' | 'physiotherapy' | 'sports_psychology';

/** @deprecated Use ServiceType instead */
export type ServiceCategory = ServiceType;

export type SubscriptionTier = 'free' | 'basic' | 'premium' | 'enterprise';

export type SubscriptionStatus = 'active' | 'past_due' | 'canceled' | 'trialing';

export type CoachingStatus = 'pending' | 'active' | 'paused' | 'ended';

/** @deprecated Use CoachingStatus instead */
export type RelationshipStatus = CoachingStatus;

export type FeatureKey =
  // Workouts
  | 'workouts_view'
  | 'workouts_create'
  | 'workouts_track'
  | 'workouts_history'
  // Nutrition
  | 'nutrition_view'
  | 'nutrition_create'
  | 'nutrition_track'
  | 'nutrition_history'
  // Periodization
  | 'periodization_view'
  | 'periodization_create'
  // Analytics
  | 'analytics_basic'
  | 'analytics_advanced'
  // Social
  | 'community_access'
  | 'challenges_access'
  // Limits
  | 'max_workouts_per_month'
  | 'max_meals_per_day'
  | 'max_students';

// ============================================================================
// DATABASE TABLES
// ============================================================================

export interface User {
  id: string;
  email: string;
  full_name: string;
  phone?: string | null;
  account_type: AccountType;
  account_status: AccountStatus;
  
  // Student fields (consolidated from old Student table)
  weight?: number | null;
  height?: number | null;
  birth_date?: string | null;
  gender?: 'male' | 'female' | 'other' | null;
  notes?: string | null;
  
  // Admin metadata
  is_super_admin?: boolean;
  admin_notes?: string | null;
  last_login_at?: string | null;
  
  // Subscription (for autonomous students)
  subscription_tier?: SubscriptionTier | null;
  subscription_status?: SubscriptionStatus | null;
  subscription_expires_at?: string | null;
  trial_ends_at?: string | null;
  
  // Professional metadata
  professional_name?: string | null;
  professional_bio?: string | null;
  cref?: string | null; // Conselho Regional de Educação Física
  crn?: string | null;  // Conselho Regional de Nutricionistas
  
  // Verification
  is_verified: boolean;
  verified_at?: string | null;
  
  // Gamification
  xp?: number;
  level?: number;
  
  // Timestamps
  created_at: string;
  updated_at?: string;
}

export interface ProfessionalService {
  id: string;
  user_id: string;
  service_type: ServiceType;
  /** @deprecated Use service_type instead */
  service_category?: ServiceCategory;
  is_active: boolean;
  certification_number?: string | null;
  certification_expires_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface Coaching {
  id: string;
  client_id: string;
  professional_id: string;
  service_type: ServiceType;
  status: CoachingStatus;
  invited_by?: string | null;
  started_at: string;
  ended_at?: string | null;
  ended_reason?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at?: string;
}

/** @deprecated Use Coaching instead */
export interface ClientProfessionalRelationship extends Coaching {
  service_category: ServiceCategory;
  relationship_status: RelationshipStatus;
}

export interface FeatureAccess {
  id: string;
  subscription_tier: SubscriptionTier;
  feature_key: FeatureKey;
  is_enabled: boolean;
  limit_value?: number | null;
  created_at: string;
}

/**
 * @deprecated Student table has been consolidated into User/profiles table.
 * Use User interface instead and filter by account_type = 'managed_student' or 'autonomous_student'
 */
export interface Student extends User {
  personal_id?: string | null;
  created_by?: string | null;
  invite_code?: string | null;
}

// ============================================================================
// CHAT TYPES
// ============================================================================

export interface Message {
  id: string;
  conversation_id: string;
  sender_id: string;
  receiver_id: string;
  content: string;
  message_type: 'text' | 'image' | 'audio' | 'file';
  media_url?: string;
  read_at?: string;
  created_at: string;
  updated_at?: string;
}

/** @deprecated Use Message instead */
export type ChatMessage = Message;

export interface Conversation {
  id: string;
  personal_id: string;
  student_id: string;
  last_message_at: string;
  created_at: string;
}

export interface ConversationWithDetails extends Conversation {
  other_user?: {
    id: string;
    full_name: string;
    email: string;
  };
  last_message?: Message;
  unread_count?: number;
}

// ============================================================================
// WORKOUT FEEDBACK TYPES
// ============================================================================

export interface WorkoutFeedback {
  id: string;
  workout_log_id: string;
  student_id: string;
  
  // Ratings (1-5)
  difficulty_rating?: number;
  energy_level?: number;
  satisfaction_rating?: number;
  
  // Mood
  mood?: 'great' | 'good' | 'ok' | 'tired' | 'exhausted';
  
  // Comments
  notes?: string;
  exercises_notes?: Record<string, string>;
  
  // RPE (Rate of Perceived Exertion) 1-10
  perceived_exertion?: number;
  
  created_at: string;
  updated_at: string;
}

export interface FeedbackAverages {
  avg_difficulty: number;
  avg_energy: number;
  avg_satisfaction: number;
  avg_perceived_exertion: number;
  total_feedbacks: number;
}

export interface FeedbackTrend {
  date: string;
  avg_difficulty: number;
  avg_energy: number;
  avg_satisfaction: number;
  feedback_count: number;
}

export interface MoodDistribution {
  mood: string;
  count: number;
  percentage: number;
}

// ============================================================================
// LEGACY TYPES (for backward compatibility)
// ============================================================================

/**
 * @deprecated Use AccountType instead
 */
export type UserRole = 'personal' | 'student' | 'nutritionist';

/**
 * @deprecated Use User interface instead
 */
export interface Profile {
  id: string;
  email: string;
  role: UserRole;
  full_name?: string;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// HELPER TYPES
// ============================================================================

export interface UserWithServices extends User {
  services?: ProfessionalService[];
}

export interface UserWithRelationships extends User {
  client_relationships?: Coaching[];
  professional_relationships?: Coaching[];
}

export interface ClientWithProfessionals extends User {
  professionals?: Array<{
    professional: User;
    relationship: Coaching;
  }>;
}

export interface ProfessionalWithClients extends User {
  clients?: Array<{
    client: User;
    relationship: Coaching;
  }>;
}
