// Database types for MeuPersonal
// Generated from Supabase schema

export type Database = any; // Will be generated by Supabase CLI

// ============================================================================
// ACCOUNT TYPES
// ============================================================================

export type AccountType = 'admin' | 'professional' | 'managed_student' | 'autonomous_student';

export type AccountStatus = 'pending' | 'active' | 'rejected' | 'suspended';

export type ServiceCategory = 'training' | 'nutrition' | 'physiotherapy' | 'psychology';

export type SubscriptionTier = 'free' | 'basic' | 'premium' | 'enterprise';

export type SubscriptionStatus = 'active' | 'past_due' | 'canceled' | 'trialing';

export type RelationshipStatus = 'pending' | 'active' | 'paused' | 'ended';

export type FeatureKey =
  // Workouts
  | 'workouts_view'
  | 'workouts_create'
  | 'workouts_track'
  | 'workouts_history'
  // Nutrition
  | 'nutrition_view'
  | 'nutrition_create'
  | 'nutrition_track'
  | 'nutrition_history'
  // Periodization
  | 'periodization_view'
  | 'periodization_create'
  // Analytics
  | 'analytics_basic'
  | 'analytics_advanced'
  // Social
  | 'community_access'
  | 'challenges_access'
  // Limits
  | 'max_workouts_per_month'
  | 'max_meals_per_day'
  | 'max_students';

// ============================================================================
// DATABASE TABLES
// ============================================================================

export interface User {
  id: string;
  email: string;
  full_name: string;
  account_type: AccountType;
  account_status: AccountStatus;
  
  // Admin metadata
  is_super_admin?: boolean;
  admin_notes?: string | null;
  last_login_at?: string | null;
  
  // Subscription (for autonomous students)
  subscription_tier?: SubscriptionTier | null;
  subscription_status?: SubscriptionStatus | null;
  subscription_expires_at?: string | null;
  trial_ends_at?: string | null;
  
  // Professional metadata
  professional_name?: string | null;
  professional_bio?: string | null;
  cref?: string | null; // Conselho Regional de Educação Física
  crn?: string | null;  // Conselho Regional de Nutricionistas
  
  // Verification
  is_verified: boolean;
  verified_at?: string | null;
  
  // Timestamps
  created_at: string;
  updated_at: string;
}

export interface ProfessionalService {
  id: string;
  user_id: string;
  service_category: ServiceCategory;
  is_active: boolean;
  certification_number?: string | null;
  certification_expires_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ClientProfessionalRelationship {
  id: string;
  client_id: string;
  professional_id: string;
  service_category: ServiceCategory;
  relationship_status: RelationshipStatus;
  invited_by?: string | null;
  started_at: string;
  ended_at?: string | null;
  ended_reason?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
}

export interface FeatureAccess {
  id: string;
  subscription_tier: SubscriptionTier;
  feature_key: FeatureKey;
  is_enabled: boolean;
  limit_value?: number | null;
  created_at: string;
}

export interface Student {
  id: string;
  personal_id?: string | null;
  email: string;
  full_name: string;
  phone?: string | null;
  birth_date?: string | null;
  gender?: 'male' | 'female' | 'other' | null;
  weight?: number | null;
  height?: number | null;
  notes?: string | null;
  created_by?: string | null;
  invite_code?: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// LEGACY TYPES (for backward compatibility)
// ============================================================================

/**
 * @deprecated Use AccountType instead
 */
export type UserRole = 'personal' | 'student' | 'nutritionist';

/**
 * @deprecated Use User interface instead
 */
export interface Profile {
  id: string;
  email: string;
  role: UserRole;
  full_name?: string;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// HELPER TYPES
// ============================================================================

export interface UserWithServices extends User {
  services?: ProfessionalService[];
}

export interface UserWithRelationships extends User {
  client_relationships?: ClientProfessionalRelationship[];
  professional_relationships?: ClientProfessionalRelationship[];
}

export interface ClientWithProfessionals extends User {
  professionals?: Array<{
    professional: User;
    relationship: ClientProfessionalRelationship;
  }>;
}

export interface ProfessionalWithClients extends User {
  clients?: Array<{
    client: User;
    relationship: ClientProfessionalRelationship;
  }>;
}
